#!/usr/bin/perl
use strict;
use warnings;

use Cwd qw(abs_path);
use File::Basename qw(dirname);
use lib dirname(abs_path($0));
use PrefixNotation::PnConsole;
use Getopt::Long qw(GetOptions);

my $isBatch;
GetOptions('batch|b' => \$isBatch);

if ($ARGV[0] && $isBatch) {
    PrefixNotation::PnConsole->new()->handleInput($ARGV[0]);
    exit 0;
}

PrefixNotation::PnConsole->new()->init();